# Imports and data loading

In [1]:
import numpy as np
import pandas as pd
import os
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
from ydata_profiling import ProfileReport

cwd = os.getcwd() # current working directory
ROOT_PATH = Path ('C:/Install/datasets')
os.chdir(ROOT_PATH) #change directoru

%matplotlib inline

C:\Users\natki\AppData\Local\Temp\ipykernel_7728\4156883927.py:7: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install data-profiling via `pip install data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

In [2]:
file_path_fullset = 'C:/Install/datasets/openpowerlifting-2026-04-11-50998c4c.csv'

In [3]:
df = pd.read_csv(file_path_fullset, encoding='latin1')

C:\Users\natki\AppData\Local\Temp\ipykernel_7728\85741881.py:1: DtypeWarning: Columns (33,35,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path_fullset, encoding='latin1')

In [4]:
df.shape

(3897982, 42)

In [5]:
for col in df.columns:
    pct_missing = np.mean(df[col].isnull())
    print("{} - {}%".format(col, np.round(pct_missing, 2)))

Name - 0.0%
Sex - 0.0%
Event - 0.0%
Equipment - 0.0%
Age - 0.37%
AgeClass - 0.28%
BirthYearClass - 0.35%
Division - 0.0%
BodyweightKg - 0.01%
WeightClassKg - 0.01%
Squat1Kg - 0.68%
Squat2Kg - 0.68%
Squat3Kg - 0.69%
Squat4Kg - 1.0%
Best3SquatKg - 0.3%
Bench1Kg - 0.53%
Bench2Kg - 0.54%
Bench3Kg - 0.55%
Bench4Kg - 0.99%
Best3BenchKg - 0.11%
Deadlift1Kg - 0.64%
Deadlift2Kg - 0.65%
Deadlift3Kg - 0.66%
Deadlift4Kg - 0.99%
Best3DeadliftKg - 0.25%
TotalKg - 0.07%
Place - 0.0%
Dots - 0.07%
Wilks - 0.07%
Glossbrenner - 0.07%
Goodlift - 0.15%
Tested - 0.24%
Country - 0.44%
State - 0.79%
Federation - 0.0%
ParentFederation - 0.4%
Date - 0.0%
MeetCountry - 0.0%
MeetState - 0.28%
MeetTown - 0.14%
MeetName - 0.0%
Sanctioned - 0.0%

In [6]:
print(df.duplicated().sum())
df = df.drop_duplicates()

4100

In [7]:
df["Event"].value_counts()

Event
SBD    2822882
B       762974
D       209914
BD       72305
S        19325
SB        4153
SD        2329
Name: count, dtype: int64

In [8]:
df["Sex"].value_counts()

Sex
M     2807037
F     1086682
Mx        163
Name: count, dtype: int64

In [9]:
df["WeightClassKg"].value_counts()

WeightClassKg
90      301691
75      289592
100     278753
82.5    265222
110     197728
         ...
101+         1
82.6         1
104+         1
103+         1
180          1
Name: count, Length: 402, dtype: int64

In [10]:
print(df.columns)

Index(['Name', 'Sex', 'Event', 'Equipment', 'Age', 'AgeClass',
       'BirthYearClass', 'Division', 'BodyweightKg', 'WeightClassKg',
       'Squat1Kg', 'Squat2Kg', 'Squat3Kg', 'Squat4Kg', 'Best3SquatKg',
       'Bench1Kg', 'Bench2Kg', 'Bench3Kg', 'Bench4Kg', 'Best3BenchKg',
       'Deadlift1Kg', 'Deadlift2Kg', 'Deadlift3Kg', 'Deadlift4Kg',
       'Best3DeadliftKg', 'TotalKg', 'Place', 'Dots', 'Wilks', 'Glossbrenner',
       'Goodlift', 'Tested', 'Country', 'State', 'Federation',
       'ParentFederation', 'Date', 'MeetCountry', 'MeetState', 'MeetTown',
       'MeetName', 'Sanctioned'],
      dtype='object')

In [11]:
def strip_whitespace_from_values(df: pd.DataFrame) -> pd.DataFrame:
    """Removes whitespavr from values."""
    return df.map(lambda x: x.strip() if isinstance(x, str) else x)

In [12]:
strip_whitespace_from_values(df)

,Name,Sex,Event,Equipment,Age,AgeClass,BirthYearClass,Division,BodyweightKg,WeightClassKg,...,Country,State,Federation,ParentFederation,Date,MeetCountry,MeetState,MeetTown,MeetName,Sanctioned
0,E.S. Denisenko,F,B,Raw,28.5,24-34,24-39,Open,67.3,NaN,...,NaN,NaN,GSF-Belarus,NaN,2019-06-22,Belarus,NaN,Luninets,Bison Power Cup,Yes
1,I.S. Lebetskaya,F,B,Raw,43.5,40-44,40-49,Open,73.2,NaN,...,NaN,NaN,GSF-Belarus,NaN,2019-06-22,Belarus,NaN,Luninets,Bison Power Cup,Yes
2,K. Yakimovich,F,B,Raw,26.5,24-34,24-39,Open,60.6,NaN,...,NaN,NaN,GSF-Belarus,NaN,2019-06-22,Belarus,NaN,Luninets,Bison Power Cup,Yes
3,A.G. Golneva,F,B,Raw,19.5,20-23,19-23,Juniors 17-21,50.3,NaN,...,NaN,NaN,GSF-Belarus,NaN,2019-06-22,Belarus,NaN,Luninets,Bison Power Cup,Yes
4,E.V. Marunevskaya,F,B,Raw,19.5,20-23,19-23,Juniors 17-21,63.7,NaN,...,NaN,NaN,GSF-Belarus,NaN,2019-06-22,Belarus,NaN,Luninets,Bison Power Cup,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3897977,Ibrahim Sandogji,M,SBD,Raw,17.0,16-17,14-18,Sub-Juniors,64.4,66,...,Saudi Arabia,NaN,SSSC,IPF,2022-10-13,Saudi Arabia,NaN,Riyadh,The Kingdom Classic Powerlifting Championships,Yes
3897978,Feras Alwahhabi,M,SBD,Raw,17.0,16-17,14-18,Sub-Juniors,82.9,83,...,Saudi Arabia,NaN,SSSC,IPF,2022-10-13,Saudi Arabia,NaN,Riyadh,The Kingdom Classic Powerlifting Championships,Yes
3897979,Musab Alessa,M,SBD,Raw,17.0,16-17,14-18,Sub-Juniors,91.3,93,...,Saudi Arabia,NaN,SSSC,IPF,2022-10-13,Saudi Arabia,NaN,Riyadh,The Kingdom Classic Powerlifting Championships,Yes
3897980,Ali Alholan,M,SBD,Raw,18.0,18-19,14-18,Sub-Juniors,103.6,105,...,NaN,NaN,SSSC,IPF,2022-10-13,Saudi Arabia,NaN,Riyadh,The Kingdom Classic Powerlifting Championships,Yes
3897981,Alfarooq Eissa,M,SBD,Raw,18.0,18-19,14-18,Sub-Juniors,157.3,120+,...,NaN,NaN,SSSC,IPF,2022-10-13,Saudi Arabia,NaN,Riyadh,The Kingdom Classic Powerlifting Championships,Yes

In [13]:
df.loc[:, "lifter_index"] = df["Name"].astype("category").cat.codes

In [14]:
df["lifter_index"].value_counts()

lifter_index
599169    388
340004    332
315566    295
21072     286
131375    275
         ...
599986      1
56961       1
671887      1
46010       1
319337      1
Name: count, Length: 982512, dtype: int64

In [15]:
df_indexed = df.drop(columns=["Name"])

In [16]:
#profile = ProfileReport(df_indexed, title="Prowerlifting dataset insight")

In [17]:
#profile.to_notebook_iframe()

In [18]:
#profile.to_file("unfiltered_report.html")

In [19]:
df_sbd = df_indexed[df_indexed["Event"] == "SBD"]

In [20]:
df_sbd

,Sex,Event,Equipment,Age,AgeClass,BirthYearClass,Division,BodyweightKg,WeightClassKg,Squat1Kg,...,State,Federation,ParentFederation,Date,MeetCountry,MeetState,MeetTown,MeetName,Sanctioned,lifter_index
332,M,SBD,Wraps,NaN,13-15,NaN,T1,38.8,44,40.0,...,NaN,WPC-Latvia,WPC,2011-12-17,Latvia,NaN,Dobele,Latvian Championships,Yes,688831
333,M,SBD,Wraps,NaN,NaN,NaN,Y,42.8,44,30.0,...,NaN,WPC-Latvia,WPC,2011-12-17,Latvia,NaN,Dobele,Latvian Championships,Yes,758833
334,M,SBD,Wraps,NaN,13-15,NaN,T1,47.0,48,45.0,...,NaN,WPC-Latvia,WPC,2011-12-17,Latvia,NaN,Dobele,Latvian Championships,Yes,276865
335,M,SBD,Wraps,NaN,13-15,NaN,T1,51.7,52,50.0,...,NaN,WPC-Latvia,WPC,2011-12-17,Latvia,NaN,Dobele,Latvian Championships,Yes,358376
336,M,SBD,Wraps,NaN,13-15,NaN,T1,52.8,56,50.0,...,NaN,WPC-Latvia,WPC,2011-12-17,Latvia,NaN,Dobele,Latvian Championships,Yes,259817
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3897977,M,SBD,Raw,17.0,16-17,14-18,Sub-Juniors,64.4,66,-177.5,...,NaN,SSSC,IPF,2022-10-13,Saudi Arabia,NaN,Riyadh,The Kingdom Classic Powerlifting Championships,Yes,379682
3897978,M,SBD,Raw,17.0,16-17,14-18,Sub-Juniors,82.9,83,-207.5,...,NaN,SSSC,IPF,2022-10-13,Saudi Arabia,NaN,Riyadh,The Kingdom Classic Powerlifting Championships,Yes,322197
3897979,M,SBD,Raw,17.0,16-17,14-18,Sub-Juniors,91.3,93,220.0,...,NaN,SSSC,IPF,2022-10-13,Saudi Arabia,NaN,Riyadh,The Kingdom Classic Powerlifting Championships,Yes,676579
3897980,M,SBD,Raw,18.0,18-19,14-18,Sub-Juniors,103.6,105,205.0,...,NaN,SSSC,IPF,2022-10-13,Saudi Arabia,NaN,Riyadh,The Kingdom Classic Powerlifting Championships,Yes,46091
3897981,M,SBD,Raw,18.0,18-19,14-18,Sub-Juniors,157.3,120+,220.0,...,NaN,SSSC,IPF,2022-10-13,Saudi Arabia,NaN,Riyadh,The Kingdom Classic Powerlifting Championships,Yes,45419

In [21]:
df_sbd = df_sbd[df_sbd["Equipment"] == "Raw"]

In [22]:
df_sbd

,Sex,Event,Equipment,Age,AgeClass,BirthYearClass,Division,BodyweightKg,WeightClassKg,Squat1Kg,...,State,Federation,ParentFederation,Date,MeetCountry,MeetState,MeetTown,MeetName,Sanctioned,lifter_index
372,M,SBD,Raw,33.0,24-34,24-39,O,136.60,140,290.0,...,NaN,WPC-Latvia,WPC,2011-12-17,Latvia,NaN,Dobele,Latvian Championships,Yes,540670
536,M,SBD,Raw,32.0,24-34,24-39,O,131.00,140,270.0,...,NaN,WPC-Latvia,WPC,2010-07-03,Latvia,NaN,Dobele,MonsterGym Cup,Yes,540670
12301,F,SBD,Raw,11.5,5-12,NaN,Y,63.00,67.5,55.0,...,NaN,WPC-UKR,WPC,2017-10-21,Ukraine,NaN,Kryvyi Rig,Ukrainian Cup,Yes,60463
12302,M,SBD,Raw,39.5,35-39,40-49,M1,109.65,110,210.0,...,NaN,WPC-UKR,WPC,2017-10-21,Ukraine,NaN,Kryvyi Rig,Ukrainian Cup,Yes,73189
12317,M,SBD,Raw,27.5,24-34,24-39,O,86.00,90,212.5,...,NaN,WPC-UKR,WPC,2017-10-21,Ukraine,NaN,Kryvyi Rig,Ukrainian Cup,Yes,930527
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3897977,M,SBD,Raw,17.0,16-17,14-18,Sub-Juniors,64.40,66,-177.5,...,NaN,SSSC,IPF,2022-10-13,Saudi Arabia,NaN,Riyadh,The Kingdom Classic Powerlifting Championships,Yes,379682
3897978,M,SBD,Raw,17.0,16-17,14-18,Sub-Juniors,82.90,83,-207.5,...,NaN,SSSC,IPF,2022-10-13,Saudi Arabia,NaN,Riyadh,The Kingdom Classic Powerlifting Championships,Yes,322197
3897979,M,SBD,Raw,17.0,16-17,14-18,Sub-Juniors,91.30,93,220.0,...,NaN,SSSC,IPF,2022-10-13,Saudi Arabia,NaN,Riyadh,The Kingdom Classic Powerlifting Championships,Yes,676579
3897980,M,SBD,Raw,18.0,18-19,14-18,Sub-Juniors,103.60,105,205.0,...,NaN,SSSC,IPF,2022-10-13,Saudi Arabia,NaN,Riyadh,The Kingdom Classic Powerlifting Championships,Yes,46091
3897981,M,SBD,Raw,18.0,18-19,14-18,Sub-Juniors,157.30,120+,220.0,...,NaN,SSSC,IPF,2022-10-13,Saudi Arabia,NaN,Riyadh,The Kingdom Classic Powerlifting Championships,Yes,45419

In [23]:
df_sbd["Sex"].value_counts()

Sex
M     745665
F     369361
Mx       130
Name: count, dtype: int64

In [24]:
df_sbd = df_sbd[df_sbd["Sex"] != "Mx"]

In [25]:
df_sbd["Sex"].value_counts()

Sex
M    745665
F    369361
Name: count, dtype: int64

In [26]:
print(df_sbd["WeightClassKg"].unique())

['140' '67.5' '110' '90' '75' '100' '125' '82.5' '58' '64' '72' '62' '69'
 '77' '85' '94' '105' '120' '48' '53' nan '84' '120+' '100+' '84+' '57'
 '76' '93' '83' '74' '66' '59' '52' '63' '47' '43' '56' '60' '110+' '56+'
 '82.5+' '95' '140+' '44' '90+' '105+' '125+' '83+' '63+' '69+' '65' '50'
 '70' '55' '70+' '115' '+' '40' '30' '145' '35' '145+' '97' '20' '34.9'
 '60+' '80' '66+' '75+' '67.5+' '118' '68.4' '63.9' '54.8' '73' '82.1'
 '91.1+' '51.7' '55.7' '59.8' '65.7' '70.3' '74.8' '88' '93.8' '99.7'
 '109.7' '124.7' '124.7+' '47.6' '89.8' '99.7+' '57+' '58.5' '50.5' '47.5'
 '93+' '72+' '80+' '37' '44.5' '55.5' '58.9' '72.5' '72.5+' '51.9' '60.1'
 '67.3' '82.3' '44.2' '47.8' '76+' '85+' '82' '82+' '74+' '52+' '46' '39'
 '31' '38' '33' '117.5' '117.5+' '45.3' '136+' '136' '34' '136.5' '67.1'
 '139.7' '139.7+' '36.2' '67' '127+' '92.9' '36' '61' '109' '109+' '32'
 '87' '114' '132' '148' '64+' '-74' '-93' '56.5' '81.6' '81.6+' '63.5'
 '79.3' '102' '102+' '54.5' '90.5' '90.5+' '81.5' '68' '113.5' '113.5+'
 '104.7' '104.7+' '54.4' '90.7' '90.7+' '120.2' '120.2+' '81.5+' '79.5'
 '49']

In [27]:
women_classes = [
    "43", "44", "47", "48", "52", "56", "57", "60",
    "63", "67.5", "72", "75", "82.5", "84", "90",
    "100", "110", "84+", "110+"
]

men_classes = [
    "52", "53", "56", "59", "60", "66", "67.5", "74",
    "75", "82.5", "83", "90", "93", "100", "105",
    "110", "120", "125", "140", "120+", "140+"
]

In [28]:
df_sbd = df_sbd[
    ((df_sbd["Sex"] == "F") & (df_sbd["WeightClassKg"].isin(women_classes))) |
    ((df_sbd["Sex"] == "M") & (df_sbd["WeightClassKg"].isin(men_classes)))
]

In [29]:
weight_order = [
    "43", "44", "47", "48", "52", "53", "56", "57", "59", "60",
    "63", "66", "67.5", "72", "74", "75", "82.5", "83", "90",
    "93", "100", "105", "110", "120", "125", "140", "84+", "110+", "120+", "140+"
]

In [30]:
df_sbd["WeightClassKg"].unique()

array(['140', '67.5', '110', '90', '75', '100', '125', '82.5', '72',
       '105', '120', '48', '84', '120+', '84+', '57', '93', '83', '74',
       '66', '59', '52', '63', '47', '43', '53', '56', '60', '140+', '44',
       '110+'], dtype=object)

In [31]:
df_sbd["AgeClass"].unique()

array(['24-34', '5-12', '35-39', '16-17', '40-44', '18-19', '20-23', nan,
       '45-49', '50-54', '75-79', '13-15', '60-64', '55-59', '70-74',
       '65-69', '80-84', '85-89', '90-999'], dtype=object)

In [32]:
df_sbd = df_sbd[
    df_sbd["AgeClass"].notna() &
    ~df_sbd["AgeClass"].isin(["5-12", "13-15", "16-17"])
]

In [33]:
df_sbd["AgeClass"].unique()

array(['24-34', '35-39', '40-44', '18-19', '20-23', '45-49', '50-54',
       '75-79', '60-64', '55-59', '70-74', '65-69', '80-84', '85-89',
       '90-999'], dtype=object)

In [34]:
df_sbd = df_sbd.sort_values("Date", ascending=True)
df_sbd["Year"] = df_sbd["Date"].map(lambda date: date.split("-")[0]).astype("int")

In [35]:
df_sbd["Year"].value_counts(sort=False)

Year
1965         2
1966         2
1967         2
1968         1
1969         2
1970         2
1971         2
1972         3
1973        22
1974        11
1975         1
1976         1
1977         3
1978         2
1979         2
1980         2
1981         2
1982         2
1983         3
1984         5
1985         2
1988         4
1990         3
1991         5
1992         5
1993         4
1994        13
1995        30
1996        61
1997       136
1998       229
1999       242
2000       521
2001       445
2002       662
2003       504
2004       566
2005       454
2006       658
2007       828
2008      1362
2009      1998
2010      2927
2011      5216
2012      8420
2013     13404
2014     22928
2015     32390
2016     45300
2017     55243
2018     66917
2019     72960
2020     30733
2021     55464
2022     83159
2023     99804
2024    102876
2025     97136
2026     18740
Name: count, dtype: int64

In [36]:
df_sbd.groupby(["Year", "Sex"]).size()

Year  Sex
1965  M          2
1966  M          2
1967  M          2
1968  M          1
1969  M          2
             ...
2024  M      71552
2025  F      27693
      M      69443
2026  F       5540
      M      13200
Length: 91, dtype: int64

In [37]:
df_sbd = df_sbd[df_sbd.groupby("Year")["Sex"].transform("nunique") == 2]

In [38]:
df_sbd.groupby(["Year", "Sex"]).size()

Year  Sex
1995  F          1
      M         29
1996  F          5
      M         56
1997  F         12
             ...
2024  M      71552
2025  F      27693
      M      69443
2026  F       5540
      M      13200
Length: 64, dtype: int64

In [39]:
df_sbd["Year"].dtype

dtype('int64')

In [40]:
df_sbd = df_sbd.loc[df_sbd["Year"] >= 2011]

In [41]:
df_sbd.groupby(["Year", "Sex"]).size()

Year  Sex
2011  F        819
      M       4397
2012  F       1516
      M       6904
2013  F       3033
      M      10371
2014  F       6094
      M      16834
2015  F       9463
      M      22927
2016  F      14674
      M      30626
2017  F      18624
      M      36619
2018  F      22685
      M      44232
2019  F      24717
      M      48243
2020  F      10083
      M      20650
2021  F      15580
      M      39884
2022  F      25925
      M      57234
2023  F      30085
      M      69719
2024  F      31324
      M      71552
2025  F      27693
      M      69443
2026  F       5540
      M      13200
dtype: int64

In [42]:
counts = df_sbd.groupby(["Year", "Sex"]).size()
percent = counts.groupby(level=0).apply(lambda x: x / x.sum() * 100)

percent

Year  Year  Sex
2011  2011  F      15.701687
            M      84.298313
2012  2012  F      18.004751
            M      81.995249
2013  2013  F      22.627574
            M      77.372426
2014  2014  F      26.578856
            M      73.421144
2015  2015  F      29.215807
            M      70.784193
2016  2016  F      32.392936
            M      67.607064
2017  2017  F      33.712869
            M      66.287131
2018  2018  F      33.900205
            M      66.099795
2019  2019  F      33.877467
            M      66.122533
2020  2020  F      32.808382
            M      67.191618
2021  2021  F      28.090293
            M      71.909707
2022  2022  F      31.175219
            M      68.824781
2023  2023  F      30.144082
            M      69.855918
2024  2024  F      30.448307
            M      69.551693
2025  2025  F      28.509512
            M      71.490488
2026  2026  F      29.562433
            M      70.437567
dtype: float64

In [43]:
plt.figure(figsize=(14, 6))
sns.boxplot(
    data=df_sbd,
    x="AgeClass",
    y="TotalKg",
    order=age_order
)

plt.title("Total weight lifted by age class with outliers")
plt.xticks(rotation=45)
plt.show()

NameError: name 'age_order' is not defined

In [ ]:
plt.figure(figsize=(14, 6))
sns.boxplot(
    data=df_sbd,
    x="WeightClassKg",
    y="TotalKg",
    order=weight_order
)

plt.title("Total weight lifted by weight class with outliers")
plt.xticks(rotation=45)
plt.show()

In [ ]:
def remove_iqr_outliers(group):
    Q1 = group["TotalKg"].quantile(0.25)
    Q3 = group["TotalKg"].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    return group[(group["TotalKg"] >= lower) & (group["TotalKg"] <= upper)]

In [ ]:
df_clean = df_sbd.groupby("AgeClass", group_keys=False).apply(remove_iqr_outliers)

In [ ]:
df_clean = df_clean.groupby("BodyweightKg", group_keys=False).apply(remove_iqr_outliers)

In [ ]:
df_clean = df_clean.groupby("WeightClassKg", group_keys=False).apply(remove_iqr_outliers)

In [ ]:
age_order = [
    "18-19", "20-23", "24-34",
    "35-39", "40-44", "45-49",
    "50-54", "55-59", "60-64",
    "65-69", "70-74", "75-79", "80+"
]

df_sbd["AgeClass"] = pd.Categorical(
    df_sbd["AgeClass"],
    categories=age_order,
    ordered=True
)

In [ ]:
plt.figure(figsize=(14, 6))
sns.boxplot(
    data=df_clean,
    x="AgeClass",
    y="TotalKg",
    order=age_order
)

plt.title("Total weight lifted by age class without outliers")
plt.xticks(rotation=45)
plt.show()

In [ ]:
plt.figure(figsize=(14, 6))
sns.boxplot(
    data=df_clean,
    x="WeightClassKg",
    y="TotalKg",
    order=weight_order
)

plt.title("Total weight lifted by weight class without outliers")
plt.xticks(rotation=45)
plt.show()

In [ ]:
bw_vs_total = df_clean[["Sex", "BodyweightKg", "TotalKg", "AgeClass", "WeightClassKg"]].copy()

bw_vs_total = bw_vs_total.sort_values(["BodyweightKg", "TotalKg"])

# Dropping rows with missing values.
bw_vs_total = bw_vs_total.dropna()

In [ ]:
bw_vs_total

In [ ]:
bw_vs_total[["BodyweightKg", "TotalKg"]].corr()

In [ ]:
df_sbd_m = bw_vs_total[bw_vs_total["Sex"] == "M"]

In [ ]:
df_sbd_m[["BodyweightKg", "TotalKg"]].corr()

In [ ]:
df_sbd_f = bw_vs_total[bw_vs_total["Sex"] == "F"]

In [ ]:
df_sbd_f[["BodyweightKg", "TotalKg"]].corr()

In [ ]:
print("Men:")
print("Minimum")
print(df_sbd_m["TotalKg"].min())
print("Maximum")
print(df_sbd_m["TotalKg"].max())
print("Average")
print(np.round(df_sbd_m["TotalKg"].mean(), 1))

print("\nWomen:")
print("Minimum")
print(df_sbd_f["TotalKg"].min())
print("Maximum")
print(df_sbd_f["TotalKg"].max())
print("Average")
print(np.round(df_sbd_f["TotalKg"].mean(), 1))

In [ ]:
bw_vs_total["BW_to_Total_pct"] = (bw_vs_total["BodyweightKg"] / bw_vs_total["TotalKg"]) * 100

In [ ]:
ratio_by_sex = bw_vs_total.groupby("Sex")["BW_to_Total_pct"].mean()
print(ratio_by_sex)

In [ ]:
grouped = (
    bw_vs_total
    .groupby(["WeightClassKg", "Sex"])
    .agg(
        avg_bodyweight=("BodyweightKg", "mean"),
        avg_total=("TotalKg", "mean")
    )
)

In [ ]:
grouped["ratio_pct"] = (grouped["avg_bodyweight"] / grouped["avg_total"]) * 100

In [ ]:
grouped

In [ ]:
grouped = grouped.reset_index()

grouped["WeightClassKg"] = pd.Categorical(
    grouped["WeightClassKg"],
    categories=weight_order,
    ordered=True
)

In [ ]:
plt.figure(figsize=(14, 6))
sns.barplot(
    data=grouped.reset_index(),
    x="WeightClassKg",
    y="ratio_pct",
    hue="Sex"
)

plt.ylabel("BW / Total Ratio (%)")
plt.title("Average Bodyweight-to-Total Lifted Ratio by Weight Class and Sex")
plt.show()

In [ ]:
plt.figure(figsize=(12,6))
sns.scatterplot(
    data=grouped,
    x="WeightClassKg",
    y="ratio_pct",
    hue="Sex",
    style="Sex",
    s=120
)

plt.title("Bodyweight to total lifted ratio (%) by Weight Class and Sex")
plt.xlabel("Weight Class (kg)")
plt.ylabel("Ratio (%)")
plt.grid(True, alpha=0.3)
plt.show()